groups:
  - name: test-alerts
    rules:

      - alert: UserSlashedValidators
        expr: delta(ethereum_validators_monitoring_user_validators{status="slashed"}[1m]) > 0 AND ON(nos_name) ethereum_validators_monitoring_user_validators{status="slashed"} > 0
        labels:
          severity: critical
        annotations:
          emoji: 🔪
          summary: "Operators have slashed validators"
          description: 'Number of slashed validators per operator'
          field_name: '{{ $labels.nos_name }}'
          field_value: '[{{ $value | printf "%.0f" }}](http://127.0.0.1:8082/d/3wimU2H7h/nodeoperators/?var-nos_name_var={{ urlquery $labels.nos_name }}&from={{ with query "(time() - 1200) * 1000" }}{{ . | first | value | printf "%f" }}{{ end }}&to={{ with query "time() * 1000" }}{{ . | first | value | printf "%f" }}{{ end }})'
          url: "http://127.0.0.1:8082/d/HRgPmpNnz/validators"

      - alert: DataActuality
        expr: absent(ethereum_validators_monitoring_data_actuality) OR (ethereum_validators_monitoring_data_actuality / 1000 > 3600)
        for: 1m
        labels:
          severity: critical
        annotations:
          emoji: ⏳
          summary: "Data actuality greater then 1 hour"
          resolved_summary: "Data actuality is back to normal and now less then 1 hour"
          description: "({{ humanizeDuration $value }}) It's not OK. Please, check app health"
          resolved_description: "It's OK"
          url: "http://127.0.0.1:8082/d/HRgPmpNnz/validators"

      - alert: NumValidatorsWithNegativeDelta
        expr: ethereum_validators_monitoring_validator_count_with_negative_balances_delta > 0 AND ON() changes(ethereum_validators_monitoring_epoch_number[1m]) > 0
        labels:
          severity: critical
        annotations:
          emoji: 💸
          summary: 'Operators have a negative balance delta'
          resolved_summary: 'Operators have a positive balance delta'
          description: 'Number of validators per operator who have a negative balance delta.'
          resolved_description: 'Number of validators per operator who recovered.'
          field_name: '{{ $labels.nos_name }}'
          field_value: '[{{ $value | printf "%.0f" }}](http://127.0.0.1:8082/d/3wimU2H7h/nodeoperators/?var-nos_name_var={{ urlquery $labels.nos_name }}&from={{ with query "(time() - 1200) * 1000" }}{{ . | first | value | printf "%f" }}{{ end }}&to={{ with query "time() * 1000" }}{{ . | first | value | printf "%f" }}{{ end }})'
          url: "http://127.0.0.1:8082/d/HRgPmpNnz/validators"

      - alert: NumValidatorsWithMissAttestationLastNEpoch
        expr: ethereum_validators_monitoring_validator_count_miss_attestation_last_n_epoch > 0 AND ON() changes(ethereum_validators_monitoring_epoch_number[1m]) > 0
        labels:
          severity: critical
        annotations:
          emoji: 📝❌
          summary: 'Operators have missed attestation in last {{ $labels.epoch_interval }} finalized epochs'
          resolved_summary: 'Operators not have missed attestation in last {{ $labels.epoch_interval }} finalized epochs'
          description: 'Number of validators per operator who have missed attestations.'
          resolved_description: 'Number of validators per operator who recovered.'
          field_name: '{{ $labels.nos_name }}'
          field_value: '[{{ $value | printf "%.0f" }}](http://127.0.0.1:8082/d/3wimU2H7h/nodeoperators/?var-nos_name_var={{ urlquery $labels.nos_name }}&from={{ with query "(time() - 1200) * 1000" }}{{ . | first | value | printf "%f" }}{{ end }}&to={{ with query "time() * 1000" }}{{ . | first | value | printf "%f" }}{{ end }})'
          url: "http://127.0.0.1:8082/d/HRgPmpNnz/validators"

      - alert: NumValidatorsWithHighIncDelayAttestationLastNEpoch
        expr: ethereum_validators_monitoring_validator_count_high_inc_delay_last_n_epoch > 0 AND ON() changes(ethereum_validators_monitoring_epoch_number[1m]) > 0
        labels:
          severity: critical
        annotations:
          emoji: 📝🐢
          summary: 'Operators have attestation inc. delay greater than 2 in last {{ $labels.epoch_interval }} finalized epochs'
          description: 'Number of validators per operator who have attestation with high inc. delay.'
          field_name: '{{ $labels.nos_name }}'
          field_value: '[{{ $value | printf "%.0f" }}](http://127.0.0.1:8082/d/3wimU2H7h/nodeoperators/?var-nos_name_var={{ urlquery $labels.nos_name }}&from={{ with query "(time() - 1200) * 1000" }}{{ . | first | value | printf "%f" }}{{ end }}&to={{ with query "time() * 1000" }}{{ . | first | value | printf "%f" }}{{ end }})'
          url: "http://127.0.0.1:8082/d/HRgPmpNnz/validators"

      - alert: NumValidatorsWithInvalidPropertyAttestationLastNEpoch
        expr: ethereum_validators_monitoring_validator_count_invalid_attestation_property_last_n_epoch > 0 AND ON() changes(ethereum_validators_monitoring_epoch_number[1m]) > 0
        labels:
          severity: critical
        annotations:
          emoji: '📝🏷️'
          summary: 'Operators have invalid attestation property in last {{ $labels.epoch_interval }} finalized epochs'
          description: 'Number of validators per operator who have invalid attestation property.'
          field_name: '{{ $labels.nos_name }}'
          field_value: '[{{ $value | printf "%.0f" }}](http://127.0.0.1:8082/d/3wimU2H7h/nodeoperators/?var-nos_name_var={{ urlquery $labels.nos_name }}&from={{ with query "(time() - 1200) * 1000" }}{{ . | first | value | printf "%f" }}{{ end }}&to={{ with query "time() * 1000" }}{{ . | first | value | printf "%f" }}{{ end }})'
          url: "http://127.0.0.1:8082/d/HRgPmpNnz/validators"

      - alert: NumValidatorsWithMissPropose
        expr: ethereum_validators_monitoring_validator_count_miss_propose > 0 AND ON() changes(ethereum_validators_monitoring_epoch_number[1m]) > 0
        labels:
          severity: critical
        annotations:
          emoji: 📥
          summary: 'Operators missed block propose in the last finalized epoch'
          resolved_summary: 'Operators not missed block propose in the last finalized epoch'
          description: 'Number of validators per operator who missed block propose.'
          resolved_description: 'Number of validators per operator who recovered.'
          field_name: '{{ $labels.nos_name }}'
          field_value: '[{{ $value | printf "%.0f" }}](http://127.0.0.1:8082/d/3wimU2H7h/nodeoperators/?var-nos_name_var={{ urlquery $labels.nos_name }}&from={{ with query "(time() - 1200) * 1000" }}{{ . | first | value | printf "%f" }}{{ end }}&to={{ with query "time() * 1000" }}{{ . | first | value | printf "%f" }}{{ end }})'
          url: "http://127.0.0.1:8082/d/HRgPmpNnz/validators"

      - alert: NumValidatorsWithSyncParticipationLessAvgLastNEpoch
        expr: ethereum_validators_monitoring_validator_count_with_sync_participation_less_avg_last_n_epoch > 0 AND ON() changes(ethereum_validators_monitoring_epoch_number[1m]) > 0
        labels:
          severity: critical
        annotations:
          emoji: 🔄
          summary: 'Operators sync participation less than average in last {{ $labels.epoch_interval }} finalized epochs'
          resolved_summary: 'Operators sync participation higher or equal than average in last {{ $labels.epoch_interval }} finalized epochs'
          description: 'Number of validators per operator whose sync participation less than average.'
          resolved_description: 'Number of validators per operator who recovered.'
          field_name: '{{ $labels.nos_name }}'
          field_value: '[{{ $value | printf "%.0f" }}](http://127.0.0.1:8082/d/3wimU2H7h/nodeoperators/?var-nos_name_var={{ urlquery $labels.nos_name }}&from={{ with query "(time() - 1200) * 1000" }}{{ . | first | value | printf "%f" }}{{ end }}&to={{ with query "time() * 1000" }}{{ . | first | value | printf "%f" }}{{ end }})'
          url: "http://127.0.0.1:8082/d/HRgPmpNnz/validators"

      - alert: HighRewardNumValidatorsWithSyncParticipationLessAvgLastNEpoch
        expr: ethereum_validators_monitoring_high_reward_validator_count_with_sync_participation_less_avg_last_n_epoch > 0 AND ON() changes(ethereum_validators_monitoring_epoch_number[1m]) > 0
        labels:
          severity: critical
        annotations:
          emoji: '📈🔄'
          summary: 'Operators may get high rewards in the future, but sync participation less than average in last {{ $labels.epoch_interval }} finalized epochs!'
          resolved_summary: 'Operators sync participation higher or equal than average in last {{ $labels.epoch_interval }} finalized epoch. Now may get high rewards in the future!'
          description: 'Number of validators per operator whose sync participation less than average.'
          resolved_description: 'Number of validators per operator who recovered.'
          field_name: '{{ $labels.nos_name }}'
          field_value: '[{{ $value | printf "%.0f" }}](http://127.0.0.1:8082/d/3wimU2H7h/nodeoperators/?var-nos_name_var={{ urlquery $labels.nos_name }}&from={{ with query "(time() - 1200) * 1000" }}{{ . | first | value | printf "%f" }}{{ end }}&to={{ with query "time() * 1000" }}{{ . | first | value | printf "%f" }}{{ end }})'
          url: "http://127.0.0.1:8082/d/HRgPmpNnz/validators"

      - alert: HighRewardNumValidatorsWithMissAttestationLastNEpoch
        expr: ethereum_validators_monitoring_high_reward_validator_count_miss_attestation_last_n_epoch > 0 AND ON() changes(ethereum_validators_monitoring_epoch_number[1m]) > 0
        labels:
          severity: critical
        annotations:
          emoji: '📈📝❌'
          summary: 'Operators may get high rewards in the future, but missed attestation in last {{ $labels.epoch_interval }} finalized epochs!'
          resolved_summary: 'Operators not have missed attestation in last {{ $labels.epoch_interval }} finalized epochs. Now may get high rewards in the future!'
          description: 'Number of validators per operator who have missed attestations.'
          resolved_description: 'Number of validators per operator who recovered.'
          field_name: '{{ $labels.nos_name }}'
          field_value: '[{{ $value | printf "%.0f" }}](http://127.0.0.1:8082/d/3wimU2H7h/nodeoperators/?var-nos_name_var={{ urlquery $labels.nos_name }}&from={{ with query "(time() - 1200) * 1000" }}{{ . | first | value | printf "%f" }}{{ end }}&to={{ with query "time() * 1000" }}{{ . | first | value | printf "%f" }}{{ end }})'
          url: "http://127.0.0.1:8082/d/HRgPmpNnz/validators"

      - alert: HighRewardNumValidatorsWithMissPropose
        expr: ethereum_validators_monitoring_high_reward_validator_count_miss_propose > 0 AND ON() changes(ethereum_validators_monitoring_epoch_number[1m]) > 0
        labels:
          severity: critical
        annotations:
          emoji: '📈📥'
          summary: 'Operators may get high rewards in the future, but missed block propose in the last finalized epoch!'
          resolved_summary: 'Operators not missed block propose in the last finalized epoch. Now may get high rewards in the future!'
          description: 'Number of validators per operator who missed block propose.'
          resolved_description: 'Number of validators per operator who recovered.'
          field_name: '{{ $labels.nos_name }}'
          field_value: '[{{ $value | printf "%.0f" }}](http://127.0.0.1:8082/d/3wimU2H7h/nodeoperators/?var-nos_name_var={{ urlquery $labels.nos_name }}&from={{ with query "(time() - 1200) * 1000" }}{{ . | first | value | printf "%f" }}{{ end }}&to={{ with query "time() * 1000" }}{{ . | first | value | printf "%f" }}{{ end }})'
          url: "http://127.0.0.1:8082/d/HRgPmpNnz/validators"
