global:
  scrape_interval: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'my-project'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

rule_files:
  - "alerts_rules.yml"
  - "fires.yml"

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bal_val'
    static_configs:
      - targets: ['balval_app:8080']
