---
apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: PBFA97CFB590B2093
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: true
    basicAuthUser: admin
    basicAuthPassword: foobar

  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    orgId: 1
    uid: PDEE91DDB90597936
    url: http://clickhouse:8123
    basicAuth: true
    basicAuthUser: default
    jsonData:
      graphiteVersion: 1.1
      tlsAuth: false
      tlsAuthWithCACert: false
    editable: false

  - name: Alertmanager
    type: alertmanager
    url: http://alertmanager:9093
    access: proxy
    orgId: 1
    uid: P7647F508D5F54FCB
    jsonData:
      implementation: 'prometheus'
    editable: false
